package com.Mobile;

class Exception{
	int dividend;
	int divisor;
	
	void add(){
		//Arithmetic Exception
		try {
			int quotient = dividend/divisor;
			System.out.println(quotient);
		}
	
		catch(ArithmeticException e) {
			System.out.println("Zero cant be divisor give a valid divisor");
		}
	}
	//Array IndexOutOfBoundException
	void printArr() {
		int arr[] = new int[5];
		arr[0]= 1;
		arr[1]= 2;
		arr[2]= 3;
		arr[3]= 4;
		arr[4]= 5;
		arr[5]= 6;
		for(int i = 0; i < arr.length; i++) {
			System.out.println(arr[i]);
		}
	}
	
}

public class ExceptionChecling {
	public static void main(String[] args) {
		Exception check = new Exception();
		check.add();
	}

}
